### PR TITLE
Civetweb and sc2_connection improvements

### PR DESCRIPTION
**Pull request by alkurbatov**
This improvement allows to avoid usage of custom civetweb fork. Now all patches are kept in the main repository so we can use upstream directly.

### CODE REVIEW

**Comment by alkurbatov** [comment]
@Nickrader Hey, I implemented small fix which prints reason of connection failure. Could you please check #133 again against the modern civetweb? Probably now we will see whats going on.
There is also large changes in the way we use to apply civetweb patches. Now it'll be much simpler to transition to the new civetweb.

**Comment by Nickrader** [comment]
Patch as-is works.
When put newest commit in civetweb.cmake, 073d636f8ad1a3dbda6026d3ddb82cfb764898bc, still get connection timeout.
We do see the new error message, however.

**Comment by alkurbatov** [comment]
> Patch as-is works.
> When put newest commit in civetweb.cmake, 073d636f8ad1a3dbda6026d3ddb82cfb764898bc, still get connection timeout.
> We do see the new error message, however.

Could you please show the message? Or it is exactly “connection timeout”?

**Comment by Nickrader** [comment]
```
Running test: sc2::TestAbilityRemap
Launched SC2 (C:\Program Files (x86)\StarCraft II\Versions\Base91115\SC2_x64.exe), PID: 8264
Failed to establish websocket connection: connect(127.0.0.1:8167): timeout
Waiting for connectionFailed to establish websocket connection: connect(127.0.0.1:8167): timeout
.Failed to establish websocket connection: connect(127.0.0.1:8167): timeout
.Failed to establish websocket connection: connect(127.0.0.1:8167): timeout
.Failed to establish websocket connection: connect(127.0.0.1:8167): timeout
(same message until 120 seconds have elapsed.)

.
Unable to connect to game
```

**Comment by alkurbatov** [comment]
I see, thank you!
Seems that I should look carefully into the code of patched civetweb to find out new hints.

**Comment by alkurbatov** [comment]
@Nickrader I think I found another hint.
Currently we start civetweb server before client by some reason. Later websocket client tries to connect to the server and show timeout error in case the server is down. So this could be another reason of broken connection. I added another error log to see if we have some problems with the server start. Could you please try to check the problem?

**Comment by Nickrader** [comment]
`using civetweb commit 9da7ba333fef54db11cadab2a92ef78575672d1a `
Running test: sc2::TestAbilityRemap
Launched SC2 (C:\Program Files (x86)\StarCraft II\Versions\Base91115\SC2_x64.exe), PID: 17780
Connecting to 127.0.0.1:8167...                                                                                      
Failed to establish websocket connection: connect(127.0.0.1:8167): timeout                                           
Failed to establish websocket connection: connect(127.0.0.1:8167): timeout                                           
Failed to establish websocket connection: No data received                                                           
Failed to establish websocket connection: No data received                                                           
Failed to establish websocket connection: No data received
...

`branch as-is commit b63225b7130db7e53a81c1798959462d424d0575` 
Running test: sc2::TestAbilityRemap                                                                                  
Launched SC2 (C:\Program Files (x86)\StarCraft II\Versions\Base91115\SC2_x64.exe), PID: 15456                       
Connecting to 127.0.0.1:8167...                                                                                      
Failed to establish websocket connection: connect(127.0.0.1:8167): timeout                                           
Failed to establish websocket connection: connect(127.0.0.1:8167): timeout                                           
Connected to 127.0.0.1:8167                                                                                          
Waiting for the JoinGame response.                                                                                   
WaitJoinGame finished successfully.                                                                                  
Test: sc2::TestAbilityRemap succeeded.

**Comment by alkurbatov** [comment]
Oh, I see. So there is no error and I still need to examine the civetweb's code deeper.
Thank you for the info @Nickrader

**Pull request merged**
